return {}
-- return {
--   'gbprod/yanky.nvim',
--   recommended = true,
--   desc = 'Better Yank/Paste',
--   opts = {
--     highlight = { timer = 150 },
--   },
--   keys = {
--     { 'y', '<Plug>(YankyYank)', mode = { 'n', 'x' }, desc = 'Yank Text' },
--     { 'p', '<Plug>(YankyPutAfter)', mode = { 'n', 'x' }, desc = 'Put Text After Cursor' },
--     { 'P', '<Plug>(YankyPutBefore)', mode = { 'n', 'x' }, desc = 'Put Text Before Cursor' },
--     { 'gp', '<Plug>(YankyGPutAfter)', mode = { 'n', 'x' }, desc = 'Put Text After Selection' },
--     { 'gP', '<Plug>(YankyGPutBefore)', mode = { 'n', 'x' }, desc = 'Put Text Before Selection' },
--     { '[y', '<Plug>(YankyCycleForward)', desc = 'Cycle Forward Through Yank History' },
--     { ']y', '<Plug>(YankyCycleBackward)', desc = 'Cycle Backward Through Yank History' },
--     { '<leader>p', '<Plug>(YankyPutAfterLinewise)', desc = 'Put After Cursor (Linewise)' },
--     { '<leader>P', '<Plug>(YankyPutBeforeLinewise)', desc = 'Put Before Cursor (Linewise)' },
--   },
-- }
